### ISSUE TITLE
keep game state

### ISSUE THREAD

**Issue by akyunus** [agtrlabs/sozzle#28]
Go back to home after start playing a level. when back to game level starts over.
Expected behaviour should be continue the level where you left off.
GamePlayBloc is created at game screen, that looks like the reason.

**Comment by NonymousMorlock** [comment]
Done, I went with Solution 2, and that's because I wanted to make the game state exist even after user closes the app completely, so, I used HydratedBloc to persist the game state, after they close the app and come back, the words they solved are still there
