### ISSUE TITLE
use a hint feature

### ISSUE THREAD

**Issue by akyunus** [agtrlabs/sozzle#31]
I'm not sude where the logic belogns to use a hint. Looks like it will done via GamePlayBloc. It may have its own service 
- to validate if user is available to use a hint and update user stats. 
- to select a random letter to reveal

**Comment by NonymousMorlock** [comment]
so, what will be the validation logic? I'm already guessing we will just set an `int` on the user model to keep track of how many hints they have, but how do we award hints, what conditions have to be met for a hint to be awarded

**Comment by akyunus** [comment]
Defined at #57

Boosters can be purchased by coins or, as a further improvement, Reward by ads
